import { CircuitPreset } from '../types';

export const CIRCUIT_PRESETS: CircuitPreset[] = [
  {
    id: '1ph-diode-bridge-rl',
    name: '1-Phase Diode Bridge (RL Load)',
    badge: '1Φ Uncontrolled',
    description: 'Full-wave 4-diode bridge with inductive filter for smooth DC current.',
    phaseMode: '1-phase',
    circuitType: 'full-bridge',
    switches: { S1: 'diode', S2: 'diode', S3: 'diode', S4: 'diode' },
    hasFWD: false,
    isFWDActive: false,
    loadType: 'RL',
    loadParams: { R: 20, L: 40, E: 0 },
    alpha: 0,
  },
  {
    id: '1ph-thyristor-bridge-rl',
    name: '1-Phase Fully Controlled Bridge',
    badge: '1Φ Controlled',
    description: '4-Thyristor full converter allowing variable DC voltage via firing angle α control.',
    phaseMode: '1-phase',
    circuitType: 'full-bridge',
    switches: { S1: 'thyristor', S2: 'thyristor', S3: 'thyristor', S4: 'thyristor' },
    hasFWD: false,
    isFWDActive: false,
    loadType: 'RL',
    loadParams: { R: 20, L: 50, E: 0 },
    alpha: 45,
  },
  {
    id: '1ph-semi-converter-fwd',
    name: '1-Phase Semi-Converter + FWD',
    badge: '1Φ Semi-Converter',
    description: '2 Thyristors (top) + 2 Diodes (bottom) with Freewheeling Diode to prevent negative output spikes.',
    phaseMode: '1-phase',
    circuitType: 'full-bridge',
    switches: { S1: 'thyristor', S2: 'diode', S3: 'thyristor', S4: 'diode' },
    hasFWD: true,
    isFWDActive: true,
    loadType: 'RL',
    loadParams: { R: 15, L: 60, E: 0 },
    alpha: 60,
  },
  {
    id: '3ph-diode-bridge-6pulse',
    name: '3-Phase 6-Pulse Diode Bridge',
    badge: '3Φ 6-Pulse',
    description: 'Industry standard 6-diode rectifier producing low ripple 300Hz DC output.',
    phaseMode: '3-phase',
    circuitType: 'full-bridge',
    switches: { S1: 'diode', S2: 'diode', S3: 'diode', S4: 'diode', S5: 'diode', S6: 'diode' },
    hasFWD: false,
    isFWDActive: false,
    loadType: 'RL',
    loadParams: { R: 25, L: 30, E: 0 },
    alpha: 0,
  },
  {
    id: '3ph-thyristor-converter',
    name: '3-Phase Fully Controlled Converter',
    badge: '3Φ Controlled',
    description: '6-Thyristor bridge providing wide range DC voltage regulation and regenerative braking capability.',
    phaseMode: '3-phase',
    circuitType: 'full-bridge',
    switches: { S1: 'thyristor', S2: 'thyristor', S3: 'thyristor', S4: 'thyristor', S5: 'thyristor', S6: 'thyristor' },
    hasFWD: false,
    isFWDActive: false,
    loadType: 'RL',
    loadParams: { R: 25, L: 45, E: 0 },
    alpha: 30,
  },
  {
    id: '3ph-semi-converter',
    name: '3-Phase Semi-Converter (3T + 3D)',
    badge: '3Φ Semi-Converter',
    description: '3 Controlled thyristors in top leg and 3 uncontrolled diodes in bottom leg.',
    phaseMode: '3-phase',
    circuitType: 'full-bridge',
    switches: { S1: 'thyristor', S2: 'diode', S3: 'thyristor', S4: 'diode', S5: 'thyristor', S6: 'diode' },
    hasFWD: true,
    isFWDActive: true,
    loadType: 'RL',
    loadParams: { R: 20, L: 40, E: 0 },
    alpha: 45,
  },
  {
    id: '1ph-halfwave-fwd',
    name: '1-Phase Half-Wave Rectifier + FWD',
    badge: '1Φ Half-Wave',
    description: 'Single switch converter demonstrating freewheeling diode inductor energy discharge.',
    phaseMode: '1-phase',
    circuitType: 'half-wave',
    switches: { S1: 'thyristor' },
    hasFWD: true,
    isFWDActive: true,
    loadType: 'RL',
    loadParams: { R: 15, L: 35, E: 0 },
    alpha: 30,
  },
  {
    id: 'rle-battery-charger',
    name: 'RLE Load (Battery Charger / Motor)',
    badge: 'RLE Drive',
    description: 'Controlled converter driving an active Back-EMF load (E = 80V) with continuous current.',
    phaseMode: '1-phase',
    circuitType: 'full-bridge',
    switches: { S1: 'thyristor', S2: 'thyristor', S3: 'thyristor', S4: 'thyristor' },
    hasFWD: false,
    isFWDActive: false,
    loadType: 'RLE',
    loadParams: { R: 10, L: 50, E: 80 },
    alpha: 30,
  },
  {
    id: 'inverter-regeneration-mode',
    name: 'Inversion Mode (α = 120°, Power back to AC)',
    badge: 'Line Inverter',
    description: 'RLE load operating in regeneration (inverter) mode transferring DC energy back to AC line.',
    phaseMode: '1-phase',
    circuitType: 'full-bridge',
    switches: { S1: 'thyristor', S2: 'thyristor', S3: 'thyristor', S4: 'thyristor' },
    hasFWD: false,
    isFWDActive: false,
    loadType: 'RLE',
    loadParams: { R: 8, L: 80, E: 180 },
    alpha: 120,
  }
];
